// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: remna.proto

package remna

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RemnaService_PingRemna_FullMethodName            = "/remna.RemnaService/PingRemna"
	RemnaService_GetUser_FullMethodName              = "/remna.RemnaService/GetUser"
	RemnaService_CreateUser_FullMethodName           = "/remna.RemnaService/CreateUser"
	RemnaService_UpdateUserExpiryTime_FullMethodName = "/remna.RemnaService/UpdateUserExpiryTime"
)

// RemnaServiceClient is the client API for RemnaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemnaServiceClient interface {
	PingRemna(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	UpdateUserExpiryTime(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type remnaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRemnaServiceClient(cc grpc.ClientConnInterface) RemnaServiceClient {
	return &remnaServiceClient{cc}
}

func (c *remnaServiceClient) PingRemna(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, RemnaService_PingRemna_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remnaServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, RemnaService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remnaServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, RemnaService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remnaServiceClient) UpdateUserExpiryTime(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, RemnaService_UpdateUserExpiryTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemnaServiceServer is the server API for RemnaService service.
// All implementations must embed UnimplementedRemnaServiceServer
// for forward compatibility.
type RemnaServiceServer interface {
	PingRemna(context.Context, *PingRequest) (*PingResponse, error)
	GetUser(context.Context, *GetUserRequest) (*UserResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*UserResponse, error)
	UpdateUserExpiryTime(context.Context, *UpdateUserRequest) (*UserResponse, error)
	mustEmbedUnimplementedRemnaServiceServer()
}

// UnimplementedRemnaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemnaServiceServer struct{}

func (UnimplementedRemnaServiceServer) PingRemna(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PingRemna not implemented")
}
func (UnimplementedRemnaServiceServer) GetUser(context.Context, *GetUserRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedRemnaServiceServer) CreateUser(context.Context, *CreateUserRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedRemnaServiceServer) UpdateUserExpiryTime(context.Context, *UpdateUserRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserExpiryTime not implemented")
}
func (UnimplementedRemnaServiceServer) mustEmbedUnimplementedRemnaServiceServer() {}
func (UnimplementedRemnaServiceServer) testEmbeddedByValue()                      {}

// UnsafeRemnaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemnaServiceServer will
// result in compilation errors.
type UnsafeRemnaServiceServer interface {
	mustEmbedUnimplementedRemnaServiceServer()
}

func RegisterRemnaServiceServer(s grpc.ServiceRegistrar, srv RemnaServiceServer) {
	// If the following call panics, it indicates UnimplementedRemnaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RemnaService_ServiceDesc, srv)
}

func _RemnaService_PingRemna_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemnaServiceServer).PingRemna(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemnaService_PingRemna_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemnaServiceServer).PingRemna(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemnaService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemnaServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemnaService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemnaServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemnaService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemnaServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemnaService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemnaServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemnaService_UpdateUserExpiryTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemnaServiceServer).UpdateUserExpiryTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemnaService_UpdateUserExpiryTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemnaServiceServer).UpdateUserExpiryTime(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RemnaService_ServiceDesc is the grpc.ServiceDesc for RemnaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemnaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remna.RemnaService",
	HandlerType: (*RemnaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingRemna",
			Handler:    _RemnaService_PingRemna_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _RemnaService_GetUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _RemnaService_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUserExpiryTime",
			Handler:    _RemnaService_UpdateUserExpiryTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "remna.proto",
}
