// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: remna.proto

package remna

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_remna_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remna_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_remna_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_remna_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remna_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_remna_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetUserByUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByUsernameRequest) Reset() {
	*x = GetUserByUsernameRequest{}
	mi := &file_remna_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByUsernameRequest) ProtoMessage() {}

func (x *GetUserByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remna_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByUsernameRequest.ProtoReflect.Descriptor instead.
func (*GetUserByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_remna_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetUserByTgIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tgid          string                 `protobuf:"bytes,1,opt,name=tgid,proto3" json:"tgid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByTgIDRequest) Reset() {
	*x = GetUserByTgIDRequest{}
	mi := &file_remna_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByTgIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByTgIDRequest) ProtoMessage() {}

func (x *GetUserByTgIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remna_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByTgIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByTgIDRequest) Descriptor() ([]byte, []int) {
	return file_remna_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserByTgIDRequest) GetTgid() string {
	if x != nil {
		return x.Tgid
	}
	return ""
}

type GetUserByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByEmailRequest) Reset() {
	*x = GetUserByEmailRequest{}
	mi := &file_remna_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByEmailRequest) ProtoMessage() {}

func (x *GetUserByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remna_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetUserByEmailRequest) Descriptor() ([]byte, []int) {
	return file_remna_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetUserUUIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserUUIDRequest) Reset() {
	*x = GetUserUUIDRequest{}
	mi := &file_remna_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserUUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserUUIDRequest) ProtoMessage() {}

func (x *GetUserUUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remna_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserUUIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserUUIDRequest) Descriptor() ([]byte, []int) {
	return file_remna_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserUUIDRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Tgid          string                 `protobuf:"bytes,3,opt,name=tgid,proto3" json:"tgid,omitempty"`
	Plan          string                 `protobuf:"bytes,4,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_remna_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remna_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_remna_proto_rawDescGZIP(), []int{6}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetTgid() string {
	if x != nil {
		return x.Tgid
	}
	return ""
}

func (x *CreateUserRequest) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

type UserResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Uuid           string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Username       string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Tgid           string                 `protobuf:"bytes,3,opt,name=tgid,proto3" json:"tgid,omitempty"`
	Email          string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	InternalSquads []string               `protobuf:"bytes,5,rep,name=internal_squads,json=internalSquads,proto3" json:"internal_squads,omitempty"`
	ExpiryTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expiry_time,json=expiryTime,proto3" json:"expiry_time,omitempty"`
	SubUrl         string                 `protobuf:"bytes,7,opt,name=sub_url,json=subUrl,proto3" json:"sub_url,omitempty"`
	DeviceLimit    int64                  `protobuf:"varint,8,opt,name=device_limit,json=deviceLimit,proto3" json:"device_limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_remna_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remna_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_remna_proto_rawDescGZIP(), []int{7}
}

func (x *UserResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserResponse) GetTgid() string {
	if x != nil {
		return x.Tgid
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetInternalSquads() []string {
	if x != nil {
		return x.InternalSquads
	}
	return nil
}

func (x *UserResponse) GetExpiryTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryTime
	}
	return nil
}

func (x *UserResponse) GetSubUrl() string {
	if x != nil {
		return x.SubUrl
	}
	return ""
}

func (x *UserResponse) GetDeviceLimit() int64 {
	if x != nil {
		return x.DeviceLimit
	}
	return 0
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Plan          string                 `protobuf:"bytes,3,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_remna_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remna_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_remna_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateUserRequest) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

type MultipleUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserResponse        `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipleUsersResponse) Reset() {
	*x = MultipleUsersResponse{}
	mi := &file_remna_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleUsersResponse) ProtoMessage() {}

func (x *MultipleUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remna_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleUsersResponse.ProtoReflect.Descriptor instead.
func (*MultipleUsersResponse) Descriptor() ([]byte, []int) {
	return file_remna_proto_rawDescGZIP(), []int{9}
}

func (x *MultipleUsersResponse) GetUsers() []*UserResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

type HwidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hwid          string                 `protobuf:"bytes,1,opt,name=hwid,proto3" json:"hwid,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	OsVersion     string                 `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	DeviceModel   string                 `protobuf:"bytes,5,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	UserAgent     string                 `protobuf:"bytes,6,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HwidResponse) Reset() {
	*x = HwidResponse{}
	mi := &file_remna_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HwidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HwidResponse) ProtoMessage() {}

func (x *HwidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remna_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HwidResponse.ProtoReflect.Descriptor instead.
func (*HwidResponse) Descriptor() ([]byte, []int) {
	return file_remna_proto_rawDescGZIP(), []int{10}
}

func (x *HwidResponse) GetHwid() string {
	if x != nil {
		return x.Hwid
	}
	return ""
}

func (x *HwidResponse) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *HwidResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *HwidResponse) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *HwidResponse) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *HwidResponse) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *HwidResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *HwidResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type MultipleHwidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*HwidResponse        `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipleHwidResponse) Reset() {
	*x = MultipleHwidResponse{}
	mi := &file_remna_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleHwidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleHwidResponse) ProtoMessage() {}

func (x *MultipleHwidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remna_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleHwidResponse.ProtoReflect.Descriptor instead.
func (*MultipleHwidResponse) Descriptor() ([]byte, []int) {
	return file_remna_proto_rawDescGZIP(), []int{11}
}

func (x *MultipleHwidResponse) GetDevices() []*HwidResponse {
	if x != nil {
		return x.Devices
	}
	return nil
}

type SRHRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	RequestIp     string                 `protobuf:"bytes,3,opt,name=request_ip,json=requestIp,proto3" json:"request_ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	RequestedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SRHRecordResponse) Reset() {
	*x = SRHRecordResponse{}
	mi := &file_remna_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRHRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRHRecordResponse) ProtoMessage() {}

func (x *SRHRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remna_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRHRecordResponse.ProtoReflect.Descriptor instead.
func (*SRHRecordResponse) Descriptor() ([]byte, []int) {
	return file_remna_proto_rawDescGZIP(), []int{12}
}

func (x *SRHRecordResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SRHRecordResponse) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *SRHRecordResponse) GetRequestIp() string {
	if x != nil {
		return x.RequestIp
	}
	return ""
}

func (x *SRHRecordResponse) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *SRHRecordResponse) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

type SRHHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*SRHRecordResponse   `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SRHHistoryResponse) Reset() {
	*x = SRHHistoryResponse{}
	mi := &file_remna_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRHHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRHHistoryResponse) ProtoMessage() {}

func (x *SRHHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remna_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRHHistoryResponse.ProtoReflect.Descriptor instead.
func (*SRHHistoryResponse) Descriptor() ([]byte, []int) {
	return file_remna_proto_rawDescGZIP(), []int{13}
}

func (x *SRHHistoryResponse) GetRecords() []*SRHRecordResponse {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_remna_proto protoreflect.FileDescriptor

const file_remna_proto_rawDesc = "" +
	"\n" +
	"\vremna.proto\x12\x05remna\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0e\n" +
	"\fEmptyRequest\"&\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"6\n" +
	"\x18GetUserByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"*\n" +
	"\x14GetUserByTgIDRequest\x12\x12\n" +
	"\x04tgid\x18\x01 \x01(\tR\x04tgid\"-\n" +
	"\x15GetUserByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"(\n" +
	"\x12GetUserUUIDRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"m\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04tgid\x18\x03 \x01(\tR\x04tgid\x12\x12\n" +
	"\x04plan\x18\x04 \x01(\tR\x04plan\"\x8a\x02\n" +
	"\fUserResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04tgid\x18\x03 \x01(\tR\x04tgid\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12'\n" +
	"\x0finternal_squads\x18\x05 \x03(\tR\x0einternalSquads\x12;\n" +
	"\vexpiry_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiryTime\x12\x17\n" +
	"\asub_url\x18\a \x01(\tR\x06subUrl\x12!\n" +
	"\fdevice_limit\x18\b \x01(\x03R\vdeviceLimit\"W\n" +
	"\x11UpdateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04plan\x18\x03 \x01(\tR\x04plan\"B\n" +
	"\x15MultipleUsersResponse\x12)\n" +
	"\x05users\x18\x01 \x03(\v2\x13.remna.UserResponseR\x05users\"\xb2\x02\n" +
	"\fHwidResponse\x12\x12\n" +
	"\x04hwid\x18\x01 \x01(\tR\x04hwid\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"os_version\x18\x04 \x01(\tR\tosVersion\x12!\n" +
	"\fdevice_model\x18\x05 \x01(\tR\vdeviceModel\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x06 \x01(\tR\tuserAgent\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"E\n" +
	"\x14MultipleHwidResponse\x12-\n" +
	"\adevices\x18\x01 \x03(\v2\x13.remna.HwidResponseR\adevices\"\xbd\x01\n" +
	"\x11SRHRecordResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12\x1d\n" +
	"\n" +
	"request_ip\x18\x03 \x01(\tR\trequestIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\x12=\n" +
	"\frequested_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\"H\n" +
	"\x12SRHHistoryResponse\x122\n" +
	"\arecords\x18\x01 \x03(\v2\x18.remna.SRHRecordResponseR\arecords2\xf4\x05\n" +
	"\fRemnaService\x125\n" +
	"\tPingRemna\x12\x13.remna.EmptyRequest\x1a\x13.remna.PingResponse\x12?\n" +
	"\aGetUser\x12\x1f.remna.GetUserByUsernameRequest\x1a\x13.remna.UserResponse\x12;\n" +
	"\n" +
	"CreateUser\x12\x18.remna.CreateUserRequest\x1a\x13.remna.UserResponse\x12E\n" +
	"\x14UpdateUserExpiryTime\x12\x18.remna.UpdateUserRequest\x1a\x13.remna.UserResponse\x12K\n" +
	"\x0eGetUsersByTgID\x12\x1b.remna.GetUserByTgIDRequest\x1a\x1c.remna.MultipleUsersResponse\x12M\n" +
	"\x0fGetUsersByEmail\x12\x1c.remna.GetUserByEmailRequest\x1a\x1c.remna.MultipleUsersResponse\x12@\n" +
	"\vGetAllUsers\x12\x13.remna.EmptyRequest\x1a\x1c.remna.MultipleUsersResponse\x12L\n" +
	"\x12GetUserHwidDevices\x12\x19.remna.GetUserUUIDRequest\x1a\x1b.remna.MultipleHwidResponse\x12?\n" +
	"\rGetSRHHistory\x12\x13.remna.EmptyRequest\x1a\x19.remna.SRHHistoryResponse\x12=\n" +
	"\vDisableUser\x12\x19.remna.GetUserUUIDRequest\x1a\x13.remna.UserResponse\x12<\n" +
	"\n" +
	"EnableUser\x12\x19.remna.GetUserUUIDRequest\x1a\x13.remna.UserResponseB\bZ\x06/remnab\x06proto3"

var (
	file_remna_proto_rawDescOnce sync.Once
	file_remna_proto_rawDescData []byte
)

func file_remna_proto_rawDescGZIP() []byte {
	file_remna_proto_rawDescOnce.Do(func() {
		file_remna_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remna_proto_rawDesc), len(file_remna_proto_rawDesc)))
	})
	return file_remna_proto_rawDescData
}

var file_remna_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_remna_proto_goTypes = []any{
	(*EmptyRequest)(nil),             // 0: remna.EmptyRequest
	(*PingResponse)(nil),             // 1: remna.PingResponse
	(*GetUserByUsernameRequest)(nil), // 2: remna.GetUserByUsernameRequest
	(*GetUserByTgIDRequest)(nil),     // 3: remna.GetUserByTgIDRequest
	(*GetUserByEmailRequest)(nil),    // 4: remna.GetUserByEmailRequest
	(*GetUserUUIDRequest)(nil),       // 5: remna.GetUserUUIDRequest
	(*CreateUserRequest)(nil),        // 6: remna.CreateUserRequest
	(*UserResponse)(nil),             // 7: remna.UserResponse
	(*UpdateUserRequest)(nil),        // 8: remna.UpdateUserRequest
	(*MultipleUsersResponse)(nil),    // 9: remna.MultipleUsersResponse
	(*HwidResponse)(nil),             // 10: remna.HwidResponse
	(*MultipleHwidResponse)(nil),     // 11: remna.MultipleHwidResponse
	(*SRHRecordResponse)(nil),        // 12: remna.SRHRecordResponse
	(*SRHHistoryResponse)(nil),       // 13: remna.SRHHistoryResponse
	(*timestamppb.Timestamp)(nil),    // 14: google.protobuf.Timestamp
}
var file_remna_proto_depIdxs = []int32{
	14, // 0: remna.UserResponse.expiry_time:type_name -> google.protobuf.Timestamp
	7,  // 1: remna.MultipleUsersResponse.users:type_name -> remna.UserResponse
	14, // 2: remna.HwidResponse.created_at:type_name -> google.protobuf.Timestamp
	14, // 3: remna.HwidResponse.updated_at:type_name -> google.protobuf.Timestamp
	10, // 4: remna.MultipleHwidResponse.devices:type_name -> remna.HwidResponse
	14, // 5: remna.SRHRecordResponse.requested_at:type_name -> google.protobuf.Timestamp
	12, // 6: remna.SRHHistoryResponse.records:type_name -> remna.SRHRecordResponse
	0,  // 7: remna.RemnaService.PingRemna:input_type -> remna.EmptyRequest
	2,  // 8: remna.RemnaService.GetUser:input_type -> remna.GetUserByUsernameRequest
	6,  // 9: remna.RemnaService.CreateUser:input_type -> remna.CreateUserRequest
	8,  // 10: remna.RemnaService.UpdateUserExpiryTime:input_type -> remna.UpdateUserRequest
	3,  // 11: remna.RemnaService.GetUsersByTgID:input_type -> remna.GetUserByTgIDRequest
	4,  // 12: remna.RemnaService.GetUsersByEmail:input_type -> remna.GetUserByEmailRequest
	0,  // 13: remna.RemnaService.GetAllUsers:input_type -> remna.EmptyRequest
	5,  // 14: remna.RemnaService.GetUserHwidDevices:input_type -> remna.GetUserUUIDRequest
	0,  // 15: remna.RemnaService.GetSRHHistory:input_type -> remna.EmptyRequest
	5,  // 16: remna.RemnaService.DisableUser:input_type -> remna.GetUserUUIDRequest
	5,  // 17: remna.RemnaService.EnableUser:input_type -> remna.GetUserUUIDRequest
	1,  // 18: remna.RemnaService.PingRemna:output_type -> remna.PingResponse
	7,  // 19: remna.RemnaService.GetUser:output_type -> remna.UserResponse
	7,  // 20: remna.RemnaService.CreateUser:output_type -> remna.UserResponse
	7,  // 21: remna.RemnaService.UpdateUserExpiryTime:output_type -> remna.UserResponse
	9,  // 22: remna.RemnaService.GetUsersByTgID:output_type -> remna.MultipleUsersResponse
	9,  // 23: remna.RemnaService.GetUsersByEmail:output_type -> remna.MultipleUsersResponse
	9,  // 24: remna.RemnaService.GetAllUsers:output_type -> remna.MultipleUsersResponse
	11, // 25: remna.RemnaService.GetUserHwidDevices:output_type -> remna.MultipleHwidResponse
	13, // 26: remna.RemnaService.GetSRHHistory:output_type -> remna.SRHHistoryResponse
	7,  // 27: remna.RemnaService.DisableUser:output_type -> remna.UserResponse
	7,  // 28: remna.RemnaService.EnableUser:output_type -> remna.UserResponse
	18, // [18:29] is the sub-list for method output_type
	7,  // [7:18] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_remna_proto_init() }
func file_remna_proto_init() {
	if File_remna_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remna_proto_rawDesc), len(file_remna_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_remna_proto_goTypes,
		DependencyIndexes: file_remna_proto_depIdxs,
		MessageInfos:      file_remna_proto_msgTypes,
	}.Build()
	File_remna_proto = out.File
	file_remna_proto_goTypes = nil
	file_remna_proto_depIdxs = nil
}
