FROM golang:1.25.5-alpine

WORKDIR /app
COPY go.mod go.sum ./
RUN apk update \
 && apk add --no-cache gettext

COPY . .
RUN go build -o app ./cmd/remnavawe 
CMD sh -c "envsubst < ./config/dev.yaml > ./config/dev.gen.yaml && exec ./app -c /config/dev.gen.yaml"

